[Interface]
PrivateKey = <redacted for security>
Address = 10.8.0.2/24
DNS = 8.8.8.8  

[Peer]
PublicKey = <redacted for security>
AllowedIPs = 0.0.0.0/0  
Endpoint = <SERVER_VM_IP>:51820
PersistentKeepalive = 25
